### ISSUE TITLE
Is this being maintained any more?

### ISSUE THREAD

**Issue by adrianhall** [vuepressjs/awesome-vuepress#144]
If not, I'm happy (and I'm sure there are others would would be similarly happy) to take it over.  There hasn't been any changes in a long time.

**Comment by ulivz** [comment]
Of course not, thanks for your question, we'll handle existing PRs ASAP.

**Comment by adrianhall** [comment]
Thanks,

I didn't want to come over like that - just offer to help.  I'm glad someone is paying attention!
