### ISSUE TITLE
Github pages and Gitlab pages

### ISSUE THREAD

**Issue by scriptex** [vuepressjs/awesome-vuepress#56]
Hi!
This is not an issue but rather a question.
I've created two demos showing how to use VuePress to deploy a static website to Github Pages and Gitlab Pages.
Are you interested in adding these to the list here?
If so, in which section should they be added?
Thanks in advance!

**Comment by kefranabg** [comment]
Hi @scriptex, there's already a [deploy section](https://vuepress.vuejs.org/guide/deploy.html#github-pages) in the VuePress documentation. Don't you think it will be redundant content ? 😉

**Comment by scriptex** [comment]
Yeah, looks like I missed this in the documentation. Well, thanks for letting me know! :)
